// <auto-generated />
using CrudWeb.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MeuCrudMvc.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextContato : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CrudWeb.Models.Contato", b =>
                {
                    b.Property<int>("contatoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("contatoId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("contatoId"));

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("varchar(70)")
                        .HasColumnName("nome");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("varchar(80)")
                        .HasColumnName("email");

                    b.Property<string>("telefone")
                        .IsRequired()
                        .HasColumnType("varchar(14)")
                        .HasColumnName("telefone");

                    b.Property<string>("mensagem")
                     .IsRequired()
                     .HasColumnType("varchar(300)")
                     .HasColumnName("mensagem");

                    b.HasKey("contatoId");

                    b.ToTable("Contato");
                });
#pragma warning restore 612, 618
        }
    }
}
