// <auto-generated />
using CrudWeb.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MeuCrudMvc.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("ContextAssunto")]
    partial class Assuntos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CrudWeb.Models.Assunto", b =>
                {
                    b.Property<int>("assuntoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("assuntoId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("assuntoId"));

                    b.Property<string>("assunto")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("assunto");

                    b.HasKey("assuntoId");

                    b.ToTable("Assunto");
                });
#pragma warning restore 612, 618
        }
    }
}
