// <auto-generated />
using CrudWeb.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MeuCrudMvc.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("ContextContato")]
    partial class Contatos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CrudWeb.Models.Contato", b =>
                {
                    b.Property<int>("contatoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("contatoId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("contatoId"));

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nome");

                    b.HasKey("contatoId");

                    b.ToTable("Contato");
                });
#pragma warning restore 612, 618
        }
    }
}
